name: patrol_user1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.2.3
  url_launcher: ^6.1.5
  flutter_animated_splash: ^0.0.10
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.0.0
  permission_handler: ^11.0.0
  geolocator: ^9.0.2
  location: ^7.0.0
  image_picker: ^0.8.5+3
  firebase_storage: ^12.1.3
  flutter_local_notifications: ^17.2.2
  googleapis: ^12.0.0
  http: ^0.13.3
  flutter_polyline_points: ^1.0.0
  google_maps_webservice: ^0.0.15
  geocoding: ^3.0.0
  camera: ^0.11.0+2  # Ensure you're using the correct version
  intl: ^0.19.0
  path_provider: ^2.0.11
  flutter_keyboard_visibility: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/NationalAmbelem.jpeg
